name: itsukaji_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.1+9

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.5.0
  intl: ^0.17.0
  flutter_svg: ^2.0.4
  mobile_scanner: ^3.2.0
  qr_flutter: ^4.0.0
  flutter_signin_button: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter_icons:
  image_path: "assets/app_icons/app_icon.png"
  adaptive_icon_foreground: "assets/app_icons/app_icon_adaptive_foreground.png"
  adaptive_icon_background: "#50ABD3"
  android: true
  ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
