name: itsukaji_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.6+6

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  google_sign_in: ^5.4.1
  cloud_firestore: ^3.4.8
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  mobile_scanner: ^2.1.0
  qr_flutter: ^4.0.0
  flutter_signin_button: ^2.0.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#50ABD3"
  adaptive_icon_foreground: "assets/icon_adaptive_foreground.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
